function AH = AddSecondAxis(ReferenceAxisHandle, Color)

    box(ReferenceAxisHandle, 'off')

    AH = axes('Position', get(ReferenceAxisHandle, 'Position'), ...
            'XAxisLocation', 'top', ...
            'YAxisLocation', 'right',...
            'Color', 'none',...
            'YColor', Color, ...
            'box', 'off', ...
            'XTick', []);
        
    linkaxes([ReferenceAxisHandle AH],'x');


end