function SH = InformationText(AxisHandle, DateTimeBegin, DateTimeEnd, MeanWindSpeed, Frequency, yPosition)
        
    Text = [datestr(DateTimeBegin, 'yyyy-mm-dd') ...
        ' from ' datestr(DateTimeBegin, 'hh:MM:ss') ...
        ' to ' datestr(DateTimeEnd, 'hh:MM:ss') ...
        ' | ' ...
        'Time span: ' datestr(DateTimeEnd - DateTimeBegin, 'hh:MM:ss') ...
        char(10) ...
        'Mean wind speed: ' sprintf('%.1f m/s', MeanWindSpeed) ...
        ' | ' ...
        'Frequency: ' sprintf('%.2f Hz', Frequency)];

    SH = text(0, yPosition, Text, 'Units', 'normalized', 'Parent', AxisHandle);

end