function [DateTime] = ToDateTime(DateTime, WithYears, WithMonth, WithDays, WithHours, WithMinutes, WithSeconds)

DateElements    = arrayfun(@(x) datevec(x), DateTime, 'UniformOutput', false);

DateTime        = cellfun(@(x) datenum(x(1) * WithYears, ...
                                       x(2) * WithMonth, ...
                                       x(3) * WithDays, ...
                                       x(4) * WithHours, ...
                                       x(5) * WithMinutes, ...
                                       x(6) * WithSeconds), ...
                            DateElements);

end