function [FigureHandle] = CreateDinA4OptimizedFigure()
        
        FigureHandle        = figure ('name', '', ...
                                    'color', 'w', ...
                                    'PaperPositionMode', 'manual', ...
                                    'PaperUnits', 'points', ... 
                                    'PaperSize', [1400 950], ...  
                                    'PaperPosition', [0 0 1400 950], ...
                                    ...
                                    'Units', 'Points', ...
                                    'Position',[0 0 1400 950], ...
                                    ...
                                    'WindowStyle', 'docked');
                                
        figure(FigureHandle)
        clf(FigureHandle)
                                
end